version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ../api
      dockerfile: ../docker/ruby/Dockerfile
    command: /start.sh
    image: rails:dev
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${APP_CODE_PATH_HOST}/vendor/bundle:/var/www/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      API_DOMAIN: "127.0.0.1:${FRONT_PORT}"
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_AUTHORIZATION: ${IGDB_AUTHORIZATION}
      LIFF_CHANNEL_ID: ${LIFF_CHANNEL_ID}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_CHANNEL_TOKEN: ${LINE_CHANNEL_TOKEN}
    ports:
      - ${APP_PORT}:3000
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgresql-data:
