source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.7'

gem 'bootsnap', '>= 1.4.4', require: false

# 'rack-cors'
gem 'rack-cors'

# jwt
gem 'jwt'

# aws-sdk
gem 'aws-sdk'

# json_serializer
gem 'jsonapi-serializer'

# IGDBAPI
gem 'faraday'
gem 'faraday_middleware'

gem 'sassc'

group :development, :test do
  # デバッグ用
  gem 'bullet'
  gem 'pry-byebug'
  gem 'pry-rails'

  # RSpec関係用
  gem "factory_bot_rails"
  gem "rspec-rails"
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'

  # デバッグ用
  gem 'better_errors'
  gem 'binding_of_caller'

  # フォーマッタ用
  gem 'rails_best_practices'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rubycw'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "dockerfile-rails", ">= 1.4", :group => :development

# "LINE通知"
gem "line-bot-api"
