name: Fly Deploy
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: Docker build
        working-directory: ./gamearchive_backend/api
        run: |
          docker build -t $APP_NAME -f Dockerfile.prod .

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH

      - name: Fly Login
        run: flyctl auth token $FLY_API_TOKEN

      - name: Deploy to Fly
        run: flyctl deploy --app $APP_NAME --working-dir ./gamearchive_backend/api

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          author_name: "deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
